use chronos_core::entities::{ActivityEvent, DecisionRecord, TimeBlock};
use crate::summary::TimeSummary;

pub fn render_markdown(
    client_name: &str,
    project_name: &str,
    period: &str,
    summary: &TimeSummary,
    timeline: &[ActivityEvent],
    decisions: &[DecisionRecord],
    parallel_blocks: &[TimeBlock],
) -> String {
    let mut md = String::new();

    md.push_str(&format!("# Billing Report: {client_name} - {project_name}\n\n"));
    md.push_str(&format!("**Period:** {period}\n\n"));

    md.push_str("## 1. Time Summary\n\n");
    md.push_str("| Metric | Value |\n|--------|-------|\n");
    md.push_str(&format!("| Active time | {:.1} hrs |\n", summary.total_active_minutes / 60.0));
    md.push_str(&format!("| Passive time | {:.1} hrs |\n", summary.total_passive_minutes / 60.0));
    md.push_str(&format!("| Billable hours | {:.2} hrs |\n", summary.billable_hours));
    md.push_str(&format!("| Compute costs | ${:.2} |\n", summary.total_compute_only_cost));
    md.push_str(&format!("| **Total cost** | **${:.2}** |\n\n", summary.total_cost_usd));

    if !summary.by_source.is_empty() {
        md.push_str("### By Source\n\n");
        md.push_str("| Source | Active | Passive | Blocks |\n|--------|--------|---------|--------|\n");
        for (source, s) in &summary.by_source {
            md.push_str(&format!("| {} | {:.1} min | {:.1} min | {} |\n",
                source, s.active_minutes, s.passive_minutes, s.block_count));
        }
        md.push_str("\n");
    }

    md.push_str("## 2. Activity Timeline\n\n");
    if timeline.is_empty() {
        md.push_str("No activity events in this period.\n\n");
    } else {
        let display_count = timeline.len().min(50);
        for event in &timeline[..display_count] {
            let ts = event.timestamp.format("%Y-%m-%d %H:%M UTC");
            let summary_text = event.summary.as_deref().unwrap_or(&event.event_type);
            md.push_str(&format!("- **{ts}** [{source}] {summary_text}\n", source = event.source));
        }
        if timeline.len() > 50 {
            md.push_str(&format!("\n...and {} more events\n", timeline.len() - 50));
        }
        md.push_str("\n");
    }

    md.push_str("## 3. Progress Assessment\n\n*Generated by weekly Sonnet analysis.*\n\n");

    md.push_str("## 4. Decision Log\n\n");
    if decisions.is_empty() {
        md.push_str("No decisions extracted in this period.\n\n");
    } else {
        for (i, d) in decisions.iter().enumerate() {
            md.push_str(&format!("### Decision {}\n\n**{}**\n\n", i + 1, d.summary));
            if let Some(ref alt) = d.alternatives { md.push_str(&format!("Alternatives: {alt}\n\n")); }
            if let Some(ref rationale) = d.rationale { md.push_str(&format!("Rationale: {rationale}\n\n")); }
        }
    }

    if !parallel_blocks.is_empty() {
        md.push_str("## 5. Parallel Session Detail\n\n");
        md.push_str("| Label | Duration | Cost |\n|-------|----------|------|\n");
        for b in parallel_blocks {
            let label = b.parallel_label.as_deref().unwrap_or("(unlabeled)");
            md.push_str(&format!("| {} | {:.1} min | ${:.2} |\n", label, b.duration_minutes, b.cost_usd.unwrap_or(0.0)));
        }
        md.push_str("\n");
    }

    md.push_str("---\n*Generated by Chronos*\n");
    md
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::summary::{SourceSummary, TimeSummary};
    use std::collections::HashMap;

    #[test]
    fn renders_basic_report() {
        let mut by_source = HashMap::new();
        by_source.insert("claude".into(), SourceSummary {
            active_minutes: 120.0, passive_minutes: 30.0, compute_cost: 0.0, block_count: 3,
        });

        let summary = TimeSummary {
            period_start: "2026-05-01T00:00:00Z".parse().unwrap(),
            period_end: "2026-05-06T23:59:59Z".parse().unwrap(),
            total_active_minutes: 120.0, total_passive_minutes: 30.0,
            total_compute_only_cost: 1.50, total_evidence_minutes: 0.0,
            billable_hours: 2.05, total_cost_usd: 309.0,
            by_source, parallel_session_count: 0,
        };

        let md = render_markdown("Acme", "Website", "2026-W19", &summary, &[], &[], &[]);
        assert!(md.contains("Acme"));
        assert!(md.contains("$309.00"));
        assert!(md.contains("2.05 hrs"));
    }
}
